In [1]:
import sys
sys.path.append('../')

from lib import libdata
import pandas as pd

In [2]:
# Input file
raw_data_file = 'MStoCIRC/result.mstocirc.hsa/circ_draw.txt'

# Output files
circrnas_file = libdata.CIRCODAN_PATH + 'datasets/06_MStoCIRC_hsa.fa'
gtf_file = libdata.CIRCODAN_PATH + 'datasets/06_MStoCIRC_hsa.gtf'

In [3]:
cols = ['circRNAname', 'circRNA_length', 'CORF_start', 'CORF_end', 'IRES_start', 'IRES_end', 'exon_position', 'informa', 'nt_sequence', 'aa_sequence']
df_data = pd.read_csv(raw_data_file, header=None, names=cols, comment='#')
df_data

,circRNAname,circRNA_length,CORF_start,CORF_end,IRES_start,IRES_end,exon_position,informa,nt_sequence,aa_sequence
0,hsa_circ_0001386,702,189,714,1,50,0-702,NaN,TAAGACTTTGACCCCGACGCAGGCTTCAGTGATTGCCGCGGATCAG...,GETLGIIGLVR-MSGVRPPIMNGPLHPRPLVALLDGRDCTVEMPIL...
1,hsa_circ_0004488,861,129,936,1,50,0-861,NaN,GAGGAATTTTGTTGTCAGAGAATAAAAGGAGGTTGTCCATAATTGA...,SVAAIHPSLEIPRGILL-MFCVTPPELETKMNITKGGLVLFSANSN...
2,hsa_circ_0008350,446,167,509,1,50,0-446,NaN,CTACAAGCCTATCGTGGAATTCATCGATGCACAATTCGAGGCCTAC...,QYPWGTVQATSLSWNSSMHNSR-MKKLDSKVNIIPIIAKADAISKS...
3,hsa_circ_0009637,607,523,631,151,200,0-607,NaN,GTGGGGCCCCAGAGCGACGCTGAGTGCGTGCGGGACTCGGAGTACG...,GNPTVEVDLFTSKGGAPER-MSILKIHAREIFDSRGNPTVEVDLFT...
4,hsa_circ_0012222,2425,2380,2461,1,50,0-2425,NaN,AGCCTCCCAGAGCTGCAGATAGAAATCATTGCTGACTACGAGGTGC...,THQGLSSSLKP-MLPKIKTHQGLSSSLKPPRAADRNHC*
...,...,...,...,...,...,...,...,...,...,...
1034,hsa_circ_0067136,145,3,297,0,0,0-145,NaN,GTATGAACAGGAGCATGCTGCTATCCAGGATAAGCTCTTCCAGGTG...,WYEQEHAAIQDK-MNRSMLLSRISSSRWQRGKERLPPSTPRHPCPR...
1035,hsa_circ_0071730,483,29,1448,0,0,0-483,NaN,GGTTGTGGACTTCCTGCTGAAGGCCATCATGCGCACCATGTGGTTC...,GAVVDFLLK-MRTMWFAGGFHRVAVKGRQALPTEAAILTLAPHSSY...
1036,hsa_circ_0074586,96,21,288,0,0,0-96,NaN,TCTTCCAGGAGTTCATCAAGATGACCAACTATGACGTGGAGCACAC...,VFQEFIK-MTNYDVEHTIKKEMSGDVRDAFVAIVFQEFIKMTNYDV...
1037,hsa_circ_0091148,525,65,1574,0,0,0-525,NaN,GATTAAGGCTGCTGTCCCAAGCATCAAATTCTGCTTGGACAATGGA...,ALESPERPFLAILGGIK-MSHLGRPDGVPMPDKYSLEPVAVELKSL...
1038,hsa_circ_0104381,171,70,514,0,0,0-171,NaN,AATAACTCTGTGTCACCCTCGGAAAGCCTCCGGGCCAGTGAGAAGC...,DVSNENNSVSPSESLR-MEAKKRKAEEKDSLSRYDSDGDKSDDLVV...

In [4]:
libdata.create_fasta_file_MStoCIRC(df_data['circRNAname'], df_data['nt_sequence'], circrnas_file)
libdata.count_sequences_in_file(circrnas_file)

1039

In [5]:
# Removing repeat sequences
n_unique_seqs = libdata.remove_repeated_sequences_in_file(circrnas_file)
n_unique_seqs

984

In [6]:
# Getting cORF end and translation_cycles
orf_end_positions = []
for _,row in df_data.iterrows():
    orf_end_positions.append(libdata.get_corf_end_position_zi(row['CORF_start']-1, row['nt_sequence']) + 1)
df_data['CORF_end_corrected'] = orf_end_positions

df_data['translation_cycles'] = df_data['CORF_end'] // df_data['circRNA_length']

df_data

,circRNAname,circRNA_length,CORF_start,CORF_end,IRES_start,IRES_end,exon_position,informa,nt_sequence,aa_sequence,CORF_end_corrected,translation_cycles
0,hsa_circ_0001386,702,189,714,1,50,0-702,NaN,TAAGACTTTGACCCCGACGCAGGCTTCAGTGATTGCCGCGGATCAG...,GETLGIIGLVR-MSGVRPPIMNGPLHPRPLVALLDGRDCTVEMPIL...,11,1
1,hsa_circ_0004488,861,129,936,1,50,0-861,NaN,GAGGAATTTTGTTGTCAGAGAATAAAAGGAGGTTGTCCATAATTGA...,SVAAIHPSLEIPRGILL-MFCVTPPELETKMNITKGGLVLFSANSN...,74,1
2,hsa_circ_0008350,446,167,509,1,50,0-446,NaN,CTACAAGCCTATCGTGGAATTCATCGATGCACAATTCGAGGCCTAC...,QYPWGTVQATSLSWNSSMHNSR-MKKLDSKVNIIPIIAKADAISKS...,62,1
3,hsa_circ_0009637,607,523,631,151,200,0-607,NaN,GTGGGGCCCCAGAGCGACGCTGAGTGCGTGCGGGACTCGGAGTACG...,GNPTVEVDLFTSKGGAPER-MSILKIHAREIFDSRGNPTVEVDLFT...,23,1
4,hsa_circ_0012222,2425,2380,2461,1,50,0-2425,NaN,AGCCTCCCAGAGCTGCAGATAGAAATCATTGCTGACTACGAGGTGC...,THQGLSSSLKP-MLPKIKTHQGLSSSLKPPRAADRNHC*,35,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1034,hsa_circ_0067136,145,3,297,0,0,0-145,NaN,GTATGAACAGGAGCATGCTGCTATCCAGGATAAGCTCTTCCAGGTG...,WYEQEHAAIQDK-MNRSMLLSRISSSRWQRGKERLPPSTPRHPCPR...,6,2
1035,hsa_circ_0071730,483,29,1448,0,0,0-483,NaN,GGTTGTGGACTTCCTGCTGAAGGCCATCATGCGCACCATGTGGTTC...,GAVVDFLLK-MRTMWFAGGFHRVAVKGRQALPTEAAILTLAPHSSY...,28,2
1036,hsa_circ_0074586,96,21,288,0,0,0-96,NaN,TCTTCCAGGAGTTCATCAAGATGACCAACTATGACGTGGAGCACAC...,VFQEFIK-MTNYDVEHTIKKEMSGDVRDAFVAIVFQEFIKMTNYDV...,20,3
1037,hsa_circ_0091148,525,65,1574,0,0,0-525,NaN,GATTAAGGCTGCTGTCCCAAGCATCAAATTCTGCTTGGACAATGGA...,ALESPERPFLAILGGIK-MSHLGRPDGVPMPDKYSLEPVAVELKSL...,64,2
1038,hsa_circ_0104381,171,70,514,0,0,0-171,NaN,AATAACTCTGTGTCACCCTCGGAAAGCCTCCGGGCCAGTGAGAAGC...,DVSNENNSVSPSESLR-MEAKKRKAEEKDSLSRYDSDGDKSDDLVV...,69,3

In [7]:
# Checking start codon
df_data['start_codon'] = df_data.apply(lambda row: row['nt_sequence'][row['CORF_start']-1:row['CORF_start']+2], axis=1)
df_data['start_codon_correct'] = df_data['start_codon'].apply(lambda sequence: sequence[-3:] in ['ATG'])
df_data[~df_data['start_codon_correct']]

,circRNAname,circRNA_length,CORF_start,CORF_end,IRES_start,IRES_end,exon_position,informa,nt_sequence,aa_sequence,CORF_end_corrected,translation_cycles,start_codon,start_codon_correct
315,hsa_circ_0010401,143,144,309,1,50,0-143,NaN,ATGGAGAAGGATGAAACTGTGAGTGACTGCTCCCCACACATAGCCA...,TKDIVNGLR-MEKDETVSDCSPHIANIGRLVEDMENKIRSTLNEIY...,143,2,,False

In [8]:
# Fixing start codon
df_data.loc[df_data['circRNAname'] == 'hsa_circ_0010401', ['CORF_start', 'CORF_end_corrected']] = [1, 22]
df_data.loc[df_data['circRNAname'] == 'hsa_circ_0010401']

,circRNAname,circRNA_length,CORF_start,CORF_end,IRES_start,IRES_end,exon_position,informa,nt_sequence,aa_sequence,CORF_end_corrected,translation_cycles,start_codon,start_codon_correct
315,hsa_circ_0010401,143,1,309,1,50,0-143,NaN,ATGGAGAAGGATGAAACTGTGAGTGACTGCTCCCCACACATAGCCA...,TKDIVNGLR-MEKDETVSDCSPHIANIGRLVEDMENKIRSTLNEIY...,22,2,,False

In [9]:
libdata.create_gtf_file_MStoCIRC(df_data, gtf_file)